# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/99b_examples-glue.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch
from fastai.text.all import *

from datasets import load_dataset, concatenate_datasets
from transformers import *

from ..utils import *
from ..data.core import *
from ..modeling.core import *

logging.set_verbosity_error()