# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/99c_examples-glue-plain-pytorch.ipynb (unless otherwise specified).

__all__ = []

# Cell
from dataclasses import dataclass

import torch
from fastai.text.all import *
from transformers import *
from datasets import load_dataset

from ..utils import *
from ..data.core import *
from ..modeling.core import *

logging.set_verbosity_error()