# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01a_data-language-modeling.ipynb (unless otherwise specified).

__all__ = []

# Cell
import ast
from functools import reduce

from ..utils import *
from .core import *

import torch
from transformers import *
from fastai2.text.all import *