# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_text-callbacks.ipynb.

# %% ../../nbs/01_text-callbacks.ipynb 3
from __future__ import annotations

import importlib, sys

import torch

from fastcore.all import *
from fastai.callback.all import *
from fastai.imports import *
from fastai.learner import *
from fastai.torch_core import *


# %% auto 0
__all__ = []
