# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"str_to_class": "00_utils.ipynb",
         "Singleton": "00_utils.ipynb",
         "ModelHelper": "00_utils.ipynb",
         "BLURR_MODEL_HELPER": "00_utils.ipynb",
         "HF_ARCHITECTURES": "00_utils.ipynb",
         "HF_TASKS_ALL": "00_utils.ipynb",
         "HF_TASKS_AUTO": "00_utils.ipynb",
         "HF_MODELS": "00_utils.ipynb",
         "ForMaskedLMTask": "00_utils.ipynb",
         "ForQuestionAnsweringTask": "00_utils.ipynb",
         "ForSequenceClassificationTask": "00_utils.ipynb",
         "ForTokenClassificationTask": "00_utils.ipynb",
         "ForPreTrainingTask": "00_utils.ipynb",
         "WithLMHeadTask": "00_utils.ipynb",
         "ForConditionalGenerationTask": "00_utils.ipynb",
         "ForMultipleChoiceTask": "00_utils.ipynb",
         "ForNextSentencePredictionTask": "00_utils.ipynb",
         "ForQuestionAnsweringSimpleTask": "00_utils.ipynb",
         "WithLMHeadModelTask": "00_utils.ipynb",
         "ForClassificationTask": "00_utils.ipynb",
         "HF_BaseInput": "01_data-core.ipynb",
         "HF_TokenizerTransform": "01_data-core.ipynb",
         "HF_BatchTransform": "01_data-core.ipynb",
         "HF_TextBlock": "01_data-core.ipynb",
         "pre_process_squad": "01c_data-question-answering.ipynb",
         "HF_QuestionAnswerInput": "01c_data-question-answering.ipynb",
         "HF_TokenTensorCategory": "01d_data-token-classification.ipynb",
         "HF_TokenCategorize": "01d_data-token-classification.ipynb",
         "HF_TokenCategoryBlock": "01d_data-token-classification.ipynb",
         "HF_TokenClassInput": "01d_data-token-classification.ipynb",
         "HF_TextGenerationInput": "01e_data-text-generation.ipynb",
         "hf_splitter": "02_modeling-core.ipynb",
         "HF_BaseModelWrapper": "02_modeling-core.ipynb",
         "HF_BaseModelCallback": "02_modeling-core.ipynb",
         "HF_QstAndAnsModelWrapper": "02c_modeling-question-answering.ipynb",
         "HF_QstAndAnsModelCallback": "02c_modeling-question-answering.ipynb",
         "MultiTargetLoss": "02c_modeling-question-answering.ipynb",
         "Learner.predict_tokens": "02d_modeling-token-classification.ipynb",
         "HF_TextGenerationModelWrapper": "02e_modeling-text-generation.ipynb",
         "text_gen_splitter": "02e_modeling-text-generation.ipynb",
         "Learner.generate_text": "02e_modeling-text-generation.ipynb"}

modules = ["utils.py",
           "data/core.py",
           "data/language_modeling.py",
           "data/question_answering.py",
           "data/token_classification.py",
           "data/text_generation.py",
           "modeling/core.py",
           "modeling/language_modeling.py",
           "modeling/question_answering.py",
           "modeling/token_classification.py",
           "modeling/text_generation.py"]

doc_url = "https://ohmeow.github.io/blurr/"

git_url = "https://github.com/ohmeow/blurr/tree/master/"

def custom_doc_links(name): return None
