# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"str_to_class": "00_utils.ipynb",
         "Singleton": "00_utils.ipynb",
         "ModelHelper": "00_utils.ipynb",
         "BLURR_MODEL_HELPER": "00_utils.ipynb",
         "HF_ARCHITECTURES": "00_utils.ipynb",
         "HF_TASKS_ALL": "00_utils.ipynb",
         "HF_TASKS_AUTO": "00_utils.ipynb",
         "HF_TokenizerTransform": "01_data-core.ipynb",
         "HF_BaseInput": "01_data-core.ipynb",
         "HF_BatchTransform": "01_data-core.ipynb",
         "pad_hf_inputs": "01_data-core.ipynb",
         "HF_TextBlock": "01_data-core.ipynb",
         "pre_process_squad": "01c_data-question-answering.ipynb",
         "HF_QuestionAnswerInput": "01c_data-question-answering.ipynb",
         "HF_QABatchTransform": "01c_data-question-answering.ipynb",
         "HF_TokenTensorCategory": "01d_data-token-classification.ipynb",
         "HF_TokenCategorize": "01d_data-token-classification.ipynb",
         "HF_TokenCategoryBlock": "01d_data-token-classification.ipynb",
         "HF_TokenClassInput": "01d_data-token-classification.ipynb",
         "HF_TokenClassBatchTransform": "01d_data-token-classification.ipynb",
         "HF_SummarizationInput": "01e_data-summarization.ipynb",
         "HF_SummarizationBatchTransform": "01e_data-summarization.ipynb",
         "hf_splitter": "02_modeling-core.ipynb",
         "HF_BaseModelWrapper": "02_modeling-core.ipynb",
         "HF_BaseModelCallback": "02_modeling-core.ipynb",
         "nn.Module.blurr_summary": "02_modeling-core.ipynb",
         "Learner.blurr_summary": "02_modeling-core.ipynb",
         "Learner.blurr_predict": "02_modeling-core.ipynb",
         "HF_QstAndAnsModelCallback": "02c_modeling-question-answering.ipynb",
         "MultiTargetLoss": "02c_modeling-question-answering.ipynb",
         "calculate_token_class_metrics": "02d_modeling-token-classification.ipynb",
         "HF_TokenClassCallback": "02d_modeling-token-classification.ipynb",
         "Learner.blurr_predict_tokens": "02d_modeling-token-classification.ipynb",
         "calculate_rouge": "02e_modeling-summarization.ipynb",
         "HF_SummarizationModelCallback": "02e_modeling-summarization.ipynb",
         "summarization_splitter": "02e_modeling-summarization.ipynb",
         "HF_MaskedLMLoss": "02e_modeling-summarization.ipynb",
         "Learner.blurr_summarize": "02e_modeling-summarization.ipynb"}

modules = ["utils.py",
           "data/core.py",
           "data/language_modeling.py",
           "data/question_answering.py",
           "data/token_classification.py",
           "data/summarization.py",
           "modeling/core.py",
           "modeling/language_modeling.py",
           "modeling/question_answering.py",
           "modeling/token_classification.py",
           "modeling/summarization.py"]

doc_url = "https://ohmeow.github.io/blurr/"

git_url = "https://github.com/ohmeow/blurr/tree/master/"

def custom_doc_links(name): return None
