# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/99e_text-examples-causal-lm-gpt2.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/99e_text-examples-causal-lm-gpt2.ipynb 5
import warnings
from transformers import *
from transformers.utils import logging as hf_logging
from fastai.text.all import *

from ...text.data.core import *
from ...text.data.language_modeling import *
from ...text.modeling.core import *
from ...text.modeling.language_modeling import *
from ...text.utils import *
from ...utils import *

# %% ../../../nbs/99e_text-examples-causal-lm-gpt2.ipynb 7
# silence all the HF warnings
warnings.simplefilter("ignore")
hf_logging.set_verbosity_error()
