# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99b_text-examples-glue.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/99b_text-examples-glue.ipynb 4
import torch
from fastai.text.all import *

from datasets import load_dataset, concatenate_datasets
from transformers import *

from ...text.data.core import *
from ...text.modeling.core import *
from ...text.utils import *
from ...utils import *

logging.set_verbosity_error()

