# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/99c_text-examples-glue-plain-pytorch.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/99c_text-examples-glue-plain-pytorch.ipynb 5
import warnings
from dataclasses import dataclass

import torch
from fastai.text.all import *
from transformers import *
from transformers.utils import logging as hf_logging
from datasets import load_dataset

from ...text.data.core import *
from ...text.modeling.core import *
from ...text.utils import *
from ...utils import *

# %% ../../../nbs/99c_text-examples-glue-plain-pytorch.ipynb 7
# silence all the HF warnings
warnings.simplefilter("ignore")
hf_logging.set_verbosity_error()
