# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99d_text-examples-multilabel.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/99d_text-examples-multilabel.ipynb 4
import os

import datasets
from transformers import *
from fastai.text.all import *
from fastai.callback.hook import _print_shapes


from ...text.data.core import *
from ...text.modeling.core import *
from ...text.utils import *
from ...utils import *

logging.set_verbosity_error()

