# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/12_modeling-seq2seq-translation.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch
from datasets import list_datasets, load_dataset
from transformers import *
from fastai.text.all import *

from ...utils import *
from ...data.core import get_blurr_tfm
from ...data.seq2seq.core import *
from ...data.seq2seq.translation import *
from ..core import *
from .core import *

logging.set_verbosity_error()